### PR TITLE
Upgrade pip

### PR DESCRIPTION
**Pull request by wakanapo**
importing grpcio with pip-19.3.1 on OSX seems to have a problem. ref. https://github.com/grpc/grpc/issues/24677
In order to resolve this issue, I want to upgrade the version of pip.

I confirmed successfully imported grpcio with this upgrade in my local.

### CODE REVIEW

**Comment by NathanHowell** [comment]
@wakanapo thanks for the PR, I'll do some tests tonight and get back to you.

**Comment by NathanHowell** [comment]
@wakanapo I'm currently running into this error on Python 3.8 and 3.9 on my mac. Have you seen something similar? other packages seem to install fine

```console
# in the rules_poetry root
$ bazel build //... --sandbox_debug
<trimmed>
ERROR: pyrsistent-0.17.3-cp38-cp38-macosx_10_14_6_x86_64.whl is not a supported wheel on this platform.

$ bazel-out/host/bin/external/bazel_tools/tools/python/py3wrapper.sh --version
Python 3.8.9
```

**Comment by wakanapo** [comment]
@NathanHowell 
I could reproduce your error. We seem to need to update wheel too.
It works after updating wheel at least on my mac.
```
$ bazel build //... --sandbox_debug
...
INFO: Elapsed time: 93.125s, Critical Path: 50.55s
INFO: 156 processes: 64 internal, 92 darwin-sandbox.
INFO: Build completed successfully, 156 total actions
```
Could you test on you mac again?


The reason I used `whl` for wheel package is I faced an error with `tar.gz`.
```
ERROR: An error occurred during the fetch of repository 'wheel_archive':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/temp2632033939759715730/wheel-0.36.2.tar.gz to /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/temp2632033939759715730: /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/tests/testdata/unicode.dist/unicodedist/���_???.py (Illegal byte sequence)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/temp2632033939759715730/wheel-0.36.2.tar.gz to /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/temp2632033939759715730: /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/tests/testdata/unicode.dist/unicodedist/���_???.py (Illegal byte sequence)
ERROR: /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/pip_archive/BUILD.bazel:4:10: @pip_archive//:pip depends on @wheel_archive//:wheel in repository @wheel_archive which failed to fetch. no such package '@wheel_archive//': java.io.IOException: Error extracting /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/temp2632033939759715730/wheel-0.36.2.tar.gz to /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/temp2632033939759715730: /private/var/tmp/_bazel_wakana/b1a0621ef74e33bae90bc36a45c25e99/external/wheel_archive/tests/testdata/unicode.dist/unicodedist/���_???.py (Illegal byte sequence)
ERROR: Analysis of target '//test:wrapt' failed; build aborted: Analysis failed
```

**Comment by wakanapo** [comment]
@NathanHowell 

Sorry for annoying you again.
How is that ↑ ?
Maybe this upgrade is not the latest one anymore, though 😅

**Comment by NathanHowell** [comment]
> @NathanHowell
> 
> Sorry for annoying you again.
> How is that ↑ ?
> Maybe this upgrade is not the latest one anymore, though 😅

Sorry I dropped the ball here. My laptop is in for service, I'm hoping to get it back later in the week. When I do I'll test and merge.

**Comment by sseveran** [comment]
Do setup tools also need to be upgraded? How bound are the tools (wheel, pip, etc...) version to the python version?

**Comment by sseveran** [comment]
@NathanHowell If you are fine with merging this let's merge it. I  am going to make a PR to allow the referencing of dev dependencies.

**Review by NathanHowell — APPROVED** [review]
@sseveran works for me

**Pull request merged**
